# Generated by Django 4.2.30 on 2026-05-10 14:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='ects_credit',
        ),
        migrations.RemoveField(
            model_name='course',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='course',
            name='offered_by',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='attendance_count',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='final_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='letter_grade',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='midterm_grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='current_gpa',
        ),
        migrations.RemoveField(
            model_name='student',
            name='enrollment_date',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='assigned_departments',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='office_hour',
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='building',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='staff_no',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
