# Generated by Django 4.2.30 on 2026-05-10 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_course_ects_credit_remove_course_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='akts',
            field=models.IntegerField(default=5),
        ),
    ]
