# Generated by Django 4.2.25 on 2026-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_course_akts'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='attendance_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='average',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='final_grade',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='grade_point',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='letter_grade',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='midterm_grade',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
